window.IF_GLOSSARY = [
  {term:"asset", definition:"Something with economic value. Cash, a home, a bond, and a share of stock can all be assets, though they have different risks and features."},
  {term:"bond", definition:"A type of investment that generally represents money lent to a government, company, or other issuer, rather than ownership."},
  {term:"borrowing", definition:"Receiving money that must be repaid, usually under agreed terms. Borrowing is different from selling ownership."},
  {term:"broker", definition:"A firm or person in the business of buying and selling investments for customers or carrying out customer orders."},
  {term:"brokerage account", definition:"An account at a brokerage firm that can hold investments and be used to place buy or sell orders."},
  {term:"business", definition:"An organization that provides goods or services. In this course, “business” and “company” are often used in the same broad sense."},
  {term:"capital", definition:"Financial resources used to start, operate, or expand a business. Capital can come from internal funds, borrowing, or selling ownership."},
  {term:"company", definition:"An organization that carries out business activity, such as providing goods or services."},
  {term:"corporation", definition:"A legal business entity that is separate from its owners. Corporate ownership can be divided into shares of stock."},
  {term:"compounding", definition:"Growth that can build on earlier growth over time. Returns are not guaranteed, and losses can also affect later results."},
  {term:"diversification", definition:"Spreading money among different investments to reduce dependence on any single one. It can reduce some risks but cannot prevent every loss."},
  {term:"dividend", definition:"Money a company may choose to distribute to shareholders from its earnings. A dividend is not guaranteed."},
  {term:"debt", definition:"Money borrowed under an agreement to repay it. Business debt commonly requires repayment of principal and may require interest."},
  {term:"earnings", definition:"The amount a company has left after subtracting its costs and expenses from the money it brings in over a period."},
  {term:"expenses", definition:"The costs a business incurs to operate, such as wages, supplies, rent, utilities, or insurance."},
  {term:"equity financing", definition:"Obtaining capital by giving investors an ownership interest rather than promising scheduled loan repayment."},
  {term:"equity", definition:"An ownership interest. Stock is also called equity because it represents ownership in a company."},
  {term:"fee", definition:"An amount charged for a service, account, or investment. Fees reduce the money left for the investor."},
  {term:"financial industry", definition:"The broad group of businesses and organizations that provide services involving money, banking, investing, lending, insurance, and markets."},
  {term:"financial market", definition:"A broad system in which financial assets or contracts are bought and sold. The stock market is one type."},
  {term:"financial goal", definition:"A result someone hopes to reach with money, such as building an emergency cushion or preparing for a future expense."},
  {term:"fraud", definition:"Intentional deception used to take money or gain an unfair benefit. Investment fraud can involve false claims, fake opportunities, or hidden facts."},
  {term:"fund", definition:"An investment that pools money from many investors and holds a collection of investments according to its rules."},
  {term:"gain", definition:"An increase in value or money received above an earlier amount. A gain is not guaranteed."},
  {term:"investment", definition:"An asset or product someone puts money into with the expectation of a possible return. Investments involve different types and levels of risk."},
  {term:"interest", definition:"The cost of borrowing money, usually stated under the loan agreement. Interest is separate from repayment of principal."},
  {term:"investing", definition:"Putting money into assets with the expectation of a possible return over time. Investing involves risk and is different from a guaranteed result."},
  {term:"investor", definition:"A person or organization that puts money into an investment and accepts the related risk."},
  {term:"issuer", definition:"A company, government, or other organization that creates and sells a security to raise money."},
  {term:"listed stock", definition:"Stock accepted for listing on a particular exchange after the company meets that exchange’s requirements."},
  {term:"order", definition:"An instruction given through a broker to buy or sell an investment under stated conditions."},
  {term:"market index", definition:"A measurement designed to track the performance of a selected group of investments. An index does not represent every security in the market."},
  {term:"primary market", definition:"The part of the securities market where newly issued securities are sold and the issuer receives the proceeds, after applicable costs."},
  {term:"principal", definition:"The original amount borrowed under a debt agreement, separate from interest and other charges."},
  {term:"profit", definition:"What remains after relevant costs and expenses are subtracted from revenue. Revenue and profit are not the same."},
  {term:"ownership", definition:"A recognized claim on part or all of something. Business ownership can include rights and risk."},
  {term:"portfolio", definition:"The collection of investments held by a person or organization."},
  {term:"private company", definition:"A company whose ownership is held privately and whose shares are not offered for general trading on a public stock market."},
  {term:"publicly traded company", definition:"A company with shares that members of the public can generally buy and sell through securities markets."},
  {term:"return", definition:"A gain or loss on money invested, including changes in value and certain payments. A positive return is never guaranteed."},
  {term:"revenue", definition:"Money a business earns from its sales or operations before costs and expenses are subtracted."},
  {term:"risk", definition:"The possibility that an outcome will differ from what was hoped for, including the possibility of losing money."},
  {term:"security", definition:"A financial instrument such as a stock or bond. Different securities represent different rights, risks, and features."},
  {term:"secondary market", definition:"The part of the securities market where existing securities are traded among investors after their original issuance."},
  {term:"share", definition:"One measured unit of ownership in a company’s stock. It is not a specific physical object owned by the company."},
  {term:"shareholder", definition:"A person or organization that owns one or more shares of a company."},
  {term:"stock", definition:"A type of security that represents an ownership interest in a company. Stock is also called equity."},
  {term:"stock exchange", definition:"An organized trading venue that brings buyers and sellers together under rules. Companies can list shares on an exchange after meeting its requirements."},
  {term:"stock market", definition:"A broad term for the organized trading of stocks through exchanges and other trading venues."},
  {term:"trading venue", definition:"An organized place or electronic system where buying and selling can be carried out. A stock exchange is one type of trading venue."},
  {term:"voting rights", definition:"The ability some shareholders have to vote on certain company matters. The exact rights depend on the type of stock."},
  {term:"Wall Street", definition:"A real street in New York City’s financial district. The phrase is also commonly used as shorthand for the U.S. financial industry or financial markets."}
];

// Short, everyday-language companions to the formal definitions above and
// the lesson-specific terms collected by the app.
window.IF_GLOSSARY_SIMPLE = {
  "asset": "Something you own or control that is worth money.",
  "bond": "You lend money to a government or company, and it promises to pay you back, usually with interest.",
  "borrowing": "Using someone else's money now and agreeing to repay it later.",
  "broker": "The company or professional that carries out investment purchases and sales for customers.",
  "brokerage account": "An account you use to hold investments and buy or sell them.",
  "business": "A group that sells products or services.",
  "capital": "Money a business can use to get started, keep operating, or grow.",
  "company": "An organization that does business.",
  "corporation": "A company that legally exists separately from the people who own it.",
  "compounding": "Your growth can earn more growth over time, like a snowball getting larger as it rolls.",
  "diversification": "Not putting all your money in one place, so one bad result hurts less.",
  "dividend": "A payment a company may give its stockholders; the company can reduce or stop it.",
  "debt": "Money that has been borrowed and must be paid back.",
  "earnings": "What a company has left after paying the costs of doing business.",
  "expenses": "The bills and costs required to run a business.",
  "equity financing": "A business raises money by selling part ownership instead of taking a loan.",
  "equity": "Ownership in something; a stock represents equity in a company.",
  "fee": "Money charged for a service or product.",
  "financial industry": "The businesses that help people bank, borrow, insure, save, and invest money.",
  "financial market": "The system where investments are bought and sold.",
  "financial goal": "Something specific you want your money to help you accomplish.",
  "fraud": "Someone deliberately lies or hides important facts to take money or gain an unfair benefit.",
  "fund": "A basket of investments bought with money pooled from many people.",
  "gain": "Money made or an increase in value.",
  "investment": "Something you put money into hoping it will grow or pay income, while accepting that you could lose money.",
  "interest": "The extra money a borrower pays for using someone else's money.",
  "investing": "Putting money into assets that may grow over time, with no guarantee of success.",
  "investor": "A person or organization that puts money into an investment.",
  "issuer": "The company or government that creates and sells a stock, bond, or other security.",
  "listed stock": "A stock approved to trade on a particular stock exchange.",
  "order": "Your instruction to a broker to buy or sell an investment.",
  "market index": "A scorecard that follows a chosen group of investments to show how that group is doing.",
  "primary market": "Where a newly created stock or bond is sold and the issuer receives the money.",
  "principal": "The original amount borrowed, before interest and fees.",
  "profit": "The money left after a business subtracts its costs from what it earned.",
  "ownership": "Having a legal share or claim in something.",
  "portfolio": "All the investments a person or organization owns together.",
  "private company": "A company whose shares are not available for anyone to buy on a public stock market.",
  "publicly traded company": "A company whose stock can be bought and sold by the public.",
  "return": "How much an investment gained or lost, including payments it produced.",
  "revenue": "All the money a business brings in before paying its expenses.",
  "risk": "The chance that the result will be worse than you hoped, including losing money.",
  "security": "A tradable financial product, such as a stock or bond.",
  "secondary market": "Where investors buy and sell stocks or bonds that already exist.",
  "share": "One unit of ownership in a company.",
  "shareholder": "Someone who owns at least one share of a company.",
  "stock": "A small piece of ownership in a company.",
  "stock exchange": "An organized marketplace where stocks are bought and sold under set rules.",
  "stock market": "The overall system people use to buy and sell stocks.",
  "trading venue": "A physical or electronic marketplace where investments can be bought and sold.",
  "voting rights": "The ability some shareholders have to vote on certain company decisions.",
  "wall street": "A real New York street and a nickname for the U.S. investing and finance world.",

  "time horizon": "How long it will be before you need to use the money.",
  "saving": "Putting money aside where keeping it available and stable matters most.",
  "emergency fund": "Money kept easy to reach for surprise bills or a loss of income.",
  "liquidity": "How easily you can turn something into spendable cash without losing much value.",
  "market risk": "The chance that falling markets will reduce the value of your investments.",
  "inflation risk": "The chance that rising prices make your money buy less in the future.",
  "market price": "The price buyers and sellers currently agree on in the market.",
  "bid": "The most a buyer is currently offering to pay.",
  "ask": "The lowest price a seller is currently willing to accept.",
  "expectations": "What people believe may happen next.",
  "valuation": "An informed estimate of what something is worth.",
  "volatility": "How sharply and often a price moves up and down.",
  "liquidity risk": "The chance that you cannot sell quickly without accepting a much lower price.",
  "risk tolerance": "How comfortable you feel when investments are uncertain or losing value.",
  "risk capacity": "How much loss your finances can actually handle without harming important needs.",
  "loss": "A drop in value or getting back less than you put in.",
  "coupon": "The interest payment a bond is scheduled to make.",
  "maturity": "The date a bond or loan is scheduled to repay the original amount.",
  "yield": "A way to compare the income an investment pays with its price.",
  "interest-rate risk": "The chance that changing interest rates make an existing bond worth less.",
  "credit risk": "The chance that a borrower cannot make the promised payments.",
  "default": "When a borrower fails to make a required payment.",
  "bond fund": "A fund whose basket is made mostly of bonds.",
  "duration": "A number that helps estimate how strongly a bond or bond fund may react to interest-rate changes.",
  "fund share": "One unit of ownership in a pooled investment fund.",
  "mutual fund": "A professionally managed basket that pools many investors' money and is priced once each trading day.",
  "net asset value": "What one fund share is worth based on the fund's assets minus what it owes.",
  "redemption": "Cashing out mutual-fund shares by selling them back to the fund.",
  "etf": "A basket of investments that can be bought and sold on an exchange during the trading day.",
  "premium": "When something trades for more than its underlying or stated value.",
  "discount": "When something trades for less than its underlying or stated value.",
  "prospectus": "The official document explaining an investment's goals, risks, costs, and rules.",
  "expense ratio": "The yearly percentage of a fund's assets used to pay its operating costs.",
  "benchmark": "A comparison point used to judge how an investment performed.",
  "concentration": "Having a large amount tied to one investment or one type of risk.",
  "exposure": "How much of your money can be affected by a particular investment or risk.",
  "asset allocation": "How you divide your investment money among stocks, bonds, cash, and other categories.",
  "asset class": "A broad family of investments that behave in similar ways, such as stocks or bonds.",
  "cash equivalent": "A short-term holding that can usually be turned into cash quickly.",
  "overlap": "When different funds or investments actually own many of the same things.",
  "sector": "A group of companies in the same part of the economy, such as healthcare or technology.",
  "issuer diversification": "Lending to several different borrowers instead of depending on one.",
  "systematic risk": "Risk that affects the whole market and cannot be completely removed by owning more investments.",
  "rebalancing": "Buying or selling enough to return your portfolio to its planned mix.",
  "correlation": "How often two investments move in the same or opposite direction.",
  "goal-first planning": "Start with what the money must do, then choose the financial tool.",
  "constraint": "A limit your plan must respect, such as time, access, or how much loss you can afford.",
  "ownership claim": "A legal share in a company's results and value.",
  "debt claim": "A borrower's legal promise to make payments to a lender.",
  "pooled investment": "One investment that combines money from many people into a shared basket.",
  "drawdown": "How far an investment has fallen from its previous high point.",
  "recovery period": "How long it takes an investment to climb back to its earlier value.",
  "deadline risk": "The danger that your investment is down just when you need the money.",
  "retrieval practice": "Trying to remember an idea without looking at the answer, which strengthens learning.",
  "mental model": "A simple picture in your mind of how several ideas work together.",
  "total return": "The complete result from price changes and income, after relevant costs.",
  "capital gain": "Money made when you sell something for more than you paid.",
  "income return": "The part of a return that came from payments such as interest or dividends.",
  "reinvestment": "Using investment payments or gains to buy more investments.",
  "percentage loss": "The size of a loss compared with the amount you started with.",
  "break-even": "The point where you have recovered your loss and are back to your starting amount.",
  "sequence of returns": "The order in which good and bad investment years happen.",
  "projection": "A calculated guess about the future based on chosen assumptions.",
  "assumption": "Something an estimate treats as true even though it may turn out differently.",
  "annualized return": "An investment result converted into an average yearly rate for comparison.",
  "net return": "The investment result you keep after costs are removed.",
  "commission": "A fee charged for completing a purchase or sale.",
  "bid-ask spread": "The small gap between what buyers offer and sellers request; that gap is a trading cost.",
  "assets-under-management fee": "A recurring fee based on a percentage of the money being managed for you.",
  "fee table": "The part of an official document that lists an investment's costs in a standard format.",
  "sales load": "A sales fee charged when buying or selling certain mutual funds.",
  "turnover": "How often a fund replaces investments inside its basket.",
  "conflict of interest": "When someone's pay or personal benefit could affect the advice they give you.",
  "surrender charge": "A fee for leaving certain financial products earlier than the contract allows for free.",
  "form crs": "A short document explaining a financial firm's services, fees, conflicts, and disciplinary record.",
  "brokerage firm": "A company that holds customer investment accounts and processes trades.",
  "custody": "Safely holding investments and keeping the official ownership records.",
  "cash account": "A brokerage account where you generally pay the full purchase price with your own money.",
  "margin account": "A brokerage account that lets you borrow money to invest, increasing both possible gains and losses.",
  "margin call": "A demand from the broker to add money or investments because borrowed investing losses became too large.",
  "market order": "An instruction to trade quickly at the best price currently available, not at a guaranteed price.",
  "limit order": "An instruction to trade only at your chosen price or a better one.",
  "execution": "The moment a buy or sell order is actually completed.",
  "ticker symbol": "The short letter code used to identify a traded investment.",
  "time in force": "The instruction that says how long an unfilled order should remain active.",
  "trade confirmation": "The receipt showing the important details of a completed investment trade.",
  "primary source": "The original record, such as a company filing or government data release.",
  "secondary source": "Someone else's explanation or reporting about original information.",
  "evidence": "Facts or information that help show whether a claim is believable.",
  "form 10-k": "A public company's detailed yearly report filed with the SEC.",
  "form 10-q": "A public company's quarterly update filed with the SEC.",
  "form 8-k": "A report a public company files when certain important events happen.",
  "shareholder report": "A fund's regular update about its results, costs, and investments.",
  "principal risk": "One of the main ways an investment could lose money or fail to meet its goal.",
  "turnover rate": "A number showing how much of a fund's portfolio was replaced during a period.",
  "cherry-picking": "Showing only the facts that look good while leaving out important bad results.",
  "survivorship bias": "Studying the winners that remain while forgetting the failures that disappeared.",
  "benchmark mismatch": "Comparing an investment with the wrong measuring stick.",
  "investment fraud": "A fake or dishonest investment offer designed to take your money.",
  "guaranteed return": "A promise that you cannot lose; be very suspicious when this is claimed for a risky investment.",
  "high-pressure tactic": "Pushing you to act immediately so you do not have time to check the facts.",
  "brokercheck": "FINRA's free website for checking a broker's work history and disciplinary record.",
  "registration": "The official filing or approval certain financial people and products are required to have.",
  "imposter scam": "A scammer pretends to be a real person, company, or government agency.",
  "edgar": "The SEC's free online library of company and investment filings.",
  "due diligence": "Doing your own careful fact-checking before making a decision.",
  "withdrawal test": "Trying to take money out to see whether an investment account is real, although a clever scam can still fake this.",
  "recovery scam": "A second scam that charges victims upfront while falsely promising to recover money already lost.",
  "account takeover": "When someone gets unauthorized control of your financial account.",
  "incident evidence": "Messages, receipts, account records, and other proof that can help investigators.",
  "decision statement": "A short written description of what you are trying to accomplish and what limits matter.",
  "decision boundary": "A rule that tells you which choices are automatically unacceptable.",
  "essential funds": "Money needed for bills, emergencies, and other important near-term needs.",
  "investment thesis": "Your evidence-based explanation of why an investment may fit your goal.",
  "exit terms": "The rules, costs, and practical steps for getting your money out.",
  "counterparty": "The person or organization responsible for keeping the promise on the other side of a deal.",
  "disconfirming evidence": "Information that suggests your current belief may be wrong.",
  "alternative": "Another choice considered for the same goal.",
  "written disclosure": "An official document that spells out terms, costs, or risks.",
  "fiduciary duty": "A legal requirement, in certain relationships, to put the client's interests first.",
  "scope of service": "Exactly what a professional has and has not agreed to do for you.",
  "disciplinary history": "The official record of certain complaints, penalties, or professional actions.",
  "financial plan": "A connected plan for your goals, money, risks, and next steps.",
  "investment plan": "Written rules explaining how your investments will serve your goals and limits.",
  "course model": "The big-picture map connecting the investing ideas taught in this course.",
  "myth": "A popular claim that sounds true but is inaccurate.",
  "qualification": "Words that explain when a claim applies and where its limits are.",
  "guarantee": "A legally meaningful promise; ordinary investment results are usually not promised.",
  "teach-back": "Explaining an idea in your own words to prove you understand it.",
  "transfer": "Using something you learned in a new situation.",
  "metacognition": "Noticing what you truly understand and what still confuses you.",
  "next action": "One clear, low-risk step you can take now.",
  "implementation": "Actually carrying out a plan after reviewing it.",
  "review date": "A scheduled day to check whether your plan still fits.",
};
