window.IF_GLOSSARY = [
  {term:"asset", definition:"Something with economic value. Cash, a home, a bond, and a share of stock can all be assets, though they have different risks and features."},
  {term:"bond", definition:"A type of investment that generally represents money lent to a government, company, or other issuer, rather than ownership."},
  {term:"borrowing", definition:"Receiving money that must be repaid, usually under agreed terms. Borrowing is different from selling ownership."},
  {term:"broker", definition:"A firm or person in the business of buying and selling investments for customers or carrying out customer orders."},
  {term:"brokerage account", definition:"An account at a brokerage firm that can hold investments and be used to place buy or sell orders."},
  {term:"business", definition:"An organization that provides goods or services. In this course, “business” and “company” are often used in the same broad sense."},
  {term:"capital", definition:"Financial resources used to start, operate, or expand a business. Capital can come from internal funds, borrowing, or selling ownership."},
  {term:"company", definition:"An organization that carries out business activity, such as providing goods or services."},
  {term:"corporation", definition:"A legal business entity that is separate from its owners. Corporate ownership can be divided into shares of stock."},
  {term:"compounding", definition:"Growth that can build on earlier growth over time. Returns are not guaranteed, and losses can also affect later results."},
  {term:"diversification", definition:"Spreading money among different investments to reduce dependence on any single one. It can reduce some risks but cannot prevent every loss."},
  {term:"dividend", definition:"Money a company may choose to distribute to shareholders from its earnings. A dividend is not guaranteed."},
  {term:"debt", definition:"Money borrowed under an agreement to repay it. Business debt commonly requires repayment of principal and may require interest."},
  {term:"earnings", definition:"The amount a company has left after subtracting its costs and expenses from the money it brings in over a period."},
  {term:"expenses", definition:"The costs a business incurs to operate, such as wages, supplies, rent, utilities, or insurance."},
  {term:"equity financing", definition:"Obtaining capital by giving investors an ownership interest rather than promising scheduled loan repayment."},
  {term:"equity", definition:"An ownership interest. Stock is also called equity because it represents ownership in a company."},
  {term:"fee", definition:"An amount charged for a service, account, or investment. Fees reduce the money left for the investor."},
  {term:"financial industry", definition:"The broad group of businesses and organizations that provide services involving money, banking, investing, lending, insurance, and markets."},
  {term:"financial market", definition:"A broad system in which financial assets or contracts are bought and sold. The stock market is one type."},
  {term:"financial goal", definition:"A result someone hopes to reach with money, such as building an emergency cushion or preparing for a future expense."},
  {term:"fraud", definition:"Intentional deception used to take money or gain an unfair benefit. Investment fraud can involve false claims, fake opportunities, or hidden facts."},
  {term:"fund", definition:"An investment that pools money from many investors and holds a collection of investments according to its rules."},
  {term:"gain", definition:"An increase in value or money received above an earlier amount. A gain is not guaranteed."},
  {term:"investment", definition:"An asset or product someone puts money into with the expectation of a possible return. Investments involve different types and levels of risk."},
  {term:"interest", definition:"The cost of borrowing money, usually stated under the loan agreement. Interest is separate from repayment of principal."},
  {term:"investing", definition:"Putting money into assets with the expectation of a possible return over time. Investing involves risk and is different from a guaranteed result."},
  {term:"investor", definition:"A person or organization that puts money into an investment and accepts the related risk."},
  {term:"issuer", definition:"A company, government, or other organization that creates and sells a security to raise money."},
  {term:"listed stock", definition:"Stock accepted for listing on a particular exchange after the company meets that exchange’s requirements."},
  {term:"order", definition:"An instruction given through a broker to buy or sell an investment under stated conditions."},
  {term:"market index", definition:"A measurement designed to track the performance of a selected group of investments. An index does not represent every security in the market."},
  {term:"primary market", definition:"The part of the securities market where newly issued securities are sold and the issuer receives the proceeds, after applicable costs."},
  {term:"principal", definition:"The original amount borrowed under a debt agreement, separate from interest and other charges."},
  {term:"profit", definition:"What remains after relevant costs and expenses are subtracted from revenue. Revenue and profit are not the same."},
  {term:"ownership", definition:"A recognized claim on part or all of something. Business ownership can include rights and risk."},
  {term:"portfolio", definition:"The collection of investments held by a person or organization."},
  {term:"private company", definition:"A company whose ownership is held privately and whose shares are not offered for general trading on a public stock market."},
  {term:"publicly traded company", definition:"A company with shares that members of the public can generally buy and sell through securities markets."},
  {term:"return", definition:"A gain or loss on money invested, including changes in value and certain payments. A positive return is never guaranteed."},
  {term:"revenue", definition:"Money a business earns from its sales or operations before costs and expenses are subtracted."},
  {term:"risk", definition:"The possibility that an outcome will differ from what was hoped for, including the possibility of losing money."},
  {term:"security", definition:"A financial instrument such as a stock or bond. Different securities represent different rights, risks, and features."},
  {term:"secondary market", definition:"The part of the securities market where existing securities are traded among investors after their original issuance."},
  {term:"share", definition:"One measured unit of ownership in a company’s stock. It is not a specific physical object owned by the company."},
  {term:"shareholder", definition:"A person or organization that owns one or more shares of a company."},
  {term:"stock", definition:"A type of security that represents an ownership interest in a company. Stock is also called equity."},
  {term:"stock exchange", definition:"An organized trading venue that brings buyers and sellers together under rules. Companies can list shares on an exchange after meeting its requirements."},
  {term:"stock market", definition:"A broad term for the organized trading of stocks through exchanges and other trading venues."},
  {term:"trading venue", definition:"An organized place or electronic system where buying and selling can be carried out. A stock exchange is one type of trading venue."},
  {term:"voting rights", definition:"The ability some shareholders have to vote on certain company matters. The exact rights depend on the type of stock."},
  {term:"Wall Street", definition:"A real street in New York City’s financial district. The phrase is also commonly used as shorthand for the U.S. financial industry or financial markets."}
];
