(function () {
  "use strict";

  const K = (term, definition) => ({term, definition});
  const S = (title, minutes, outcome, body, terms, keyIdea, exampleTitle, exampleBody, summary, check) => ({
    id: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
    title, minutes, outcome, body, definitions: terms, keyIdea,
    workedExample: {title: exampleTitle, body: exampleBody}, summary, check
  });
  const Q = (id, concept, prompt, correct, wrong1, wrong2, feedback, position = 0) => {
    const choices = [
      {text: correct, correct: true, feedback: `Correct. ${feedback}`},
      {text: wrong1, correct: false, feedback: `Not quite. ${feedback}`},
      {text: wrong2, correct: false, feedback: `Not quite. ${feedback}`}
    ];
    const options = position === 1 ? [choices[1], choices[0], choices[2]] : position === 2 ? [choices[1], choices[2], choices[0]] : choices;
    return {id, concept, prompt, options};
  };
  const lesson = (day, title, minutes, objectives, sections, quiz, recap) => ({
    id: `day-${day}`, day, courseCode: `IF ${100 + day}`, title, totalMinutes: minutes,
    level: "Introductory", objectives, sections, quiz, recap
  });

  const day1 = lesson(1, "Saving, investing, and your goals", 24,
    ["Distinguish saving from investing.", "Match a goal to a time horizon.", "Explain why emergency savings comes before taking investment risk."],
    [
      S("Give every dollar a job", 6, "Connect a financial choice to a specific purpose and date.", [
        "Money becomes easier to manage when it has a job. A financial goal names what the money is for, approximately how much is needed, and when it will be used. 'I want more money' is a wish; 'I want $1,200 for car repairs within 12 months' is a goal you can plan around.",
        "The date matters because money needed soon has less time to recover from a market decline. Before choosing an account or investment, first identify the goal, target amount, and time horizon. The product should serve the goal—not the other way around."
      ], [K("financial goal", "A specific money result connected to an amount and a time."), K("time horizon", "The length of time before money is expected to be used.")], "Start with purpose and timing before comparing products.", "Turn a wish into a goal", "Instead of 'save for emergencies,' write: 'Build a $1,000 starter emergency fund over ten months by setting aside $100 each month.'", "A useful goal combines purpose, amount, and time."),
      S("Saving and investing solve different problems", 6, "Choose saving or investing based on access, stability, and time.", [
        "Saving usually emphasizes ready access and stability. A federally insured bank or credit-union savings account can suit near-term needs and emergency money, although purchasing power may grow slowly. Investing means placing money in assets such as stocks or bonds with the expectation of a possible return over time.",
        "Investments fluctuate and can lose value. That uncertainty may be reasonable for a distant goal, but it can be damaging when a bill arrives next month. Saving and investing are partners: saving protects near-term plans; investing may support long-term growth."
      ], [K("saving", "Setting money aside with an emphasis on access and stability."), K("investing", "Putting money into assets for a possible return while accepting risk."), K("return", "The gain or loss produced by an investment.")], "The best tool depends on when the money is needed and how much uncertainty the goal can tolerate.", "Two goals, two tools", "A repair fund needed this year belongs in accessible savings. Retirement money not needed for decades may be invested, depending on the investor's circumstances and risk tolerance.", "Saving emphasizes access; investing accepts uncertainty for possible growth."),
      S("Build a shock absorber", 6, "Explain how emergency savings protects a long-term plan.", [
        "An emergency fund is money reserved for unplanned expenses such as a repair, medical bill, or temporary income loss. It is not a punishment fund; it is a shock absorber that can reduce the need to borrow at high interest or sell an investment at a bad time.",
        "There is no single perfect amount for everyone. A practical starting point is a small, reachable target, kept somewhere safe and accessible, followed by steady additions. The amount should reflect household expenses, income stability, insurance, and other support."
      ], [K("emergency fund", "Accessible savings reserved for unplanned expenses."), K("liquidity", "How quickly an asset can be converted to usable cash without a large loss.")], "Emergency savings helps long-term investments stay long term.", "The broken water heater", "Without savings, a $700 repair may create credit-card debt or force a sale. A dedicated emergency fund pays the bill while the retirement plan remains untouched.", "A cash cushion protects both daily life and long-term choices."),
      S("Match the tool to the timeline", 6, "Use goal, horizon, access, and risk as a decision sequence.", [
        "Use four questions: What is the money for? When will it be needed? Must the amount be stable? How quickly must it be accessible? These questions narrow the field before expected return enters the conversation.",
        "Avoid false precision. A long horizon does not guarantee profit, and a savings account does not remove every risk, such as inflation. The point is to choose a reasonable category and then learn its details."
      ], [K("market risk", "The possibility that market prices will fall."), K("inflation risk", "The possibility that rising prices reduce what money can buy.")], "A higher possible return is not automatically better when the money has a near deadline.", "A three-bucket sketch", "Label three buckets: emergencies, goals within three years, and goals decades away. The first two emphasize access and stability; the distant bucket may have more capacity for investment risk.", "Purpose, time, stability, and access come before product selection.")
    ],
    [
      Q("d1q1","goal","What makes a financial goal actionable?","A purpose, target amount, and time horizon","A popular investment name","A promise of the highest return","Specific details make planning possible.",1),
      Q("d1q2","saving","Which tool generally fits an emergency expense expected this year?","Accessible savings","A single volatile stock","A long lockup with a penalty","Near-term emergency money emphasizes access and stability.",2),
      Q("d1q3","investing","What distinguishes investing from saving?","Investing accepts the possibility of loss for a possible return","Investing always earns more","Saving can never pay interest","Investing involves uncertain outcomes.",0),
      Q("d1q4","emergency","Why can an emergency fund support long-term investing?","It may prevent forced selling or expensive borrowing","It guarantees investment returns","It predicts every future bill","A cash cushion absorbs unexpected costs.",1),
      Q("d1q5","horizon","What is a time horizon?","The time before money is expected to be used","The highest price an asset reached","The number of accounts someone owns","The goal date helps determine suitable risk.",2)
    ], ["Name the goal before choosing a product.", "Saving and investing serve different timelines.", "Emergency savings can protect a long-term plan."]
  );

  const day3 = lesson(3, "Why prices move and why risk is real", 24,
    ["Explain how buyers and sellers form prices.", "Separate business value from daily price movement.", "Identify major forms of investment risk."],
    [
      S("A price is an agreement at a moment",6,"Describe a market price without treating it as a permanent fact.",[
        "A market price is the amount at which a buyer and seller agree to trade at a particular moment. Buyers compete through bids; sellers offer through asks. When expectations or available orders change, the trading price can change—even when the company's buildings and products have not changed that second.",
        "Price is information, but it is not a complete verdict. It reflects current supply, demand, expectations, uncertainty, and market conditions. Different people can study the same facts and reach different conclusions."
      ],[K("market price","The price at which an investment trades in the market."),K("bid","A price a buyer is willing to pay."),K("ask","A price a seller is willing to accept.")],"Prices emerge from trading decisions, not from a guaranteed formula.","One more eager buyer","If buyers become willing to pay more while sellers hold firm, trades may occur at higher prices. If sellers urgently accept lower bids, prices may fall.","A price is a negotiated snapshot of current market interest."),
      S("Expectations move before results",6,"Explain why news can change a price before profits change.",[
        "Investors often value a company based partly on expectations about future cash flows, growth, competition, and risk. A new contract, product delay, interest-rate change, or earnings report can alter those expectations. The market reacts to the difference between what happened and what people expected—not only whether the news sounds good or bad.",
        "A strong company can have an overpriced stock, and a struggling company can sometimes rise after results are merely less bad than feared. Company quality and purchase price are connected, but they are not identical."
      ],[K("expectations","Beliefs about what may happen in the future."),K("earnings","A company's profit over a period, measured under accounting rules."),K("valuation","An estimate of what an asset may be worth.")],"Markets price anticipated futures, so surprises matter.","Good news, falling price","A company reports higher sales, but investors expected even more and worry about rising costs. The price falls because the full report disappointed expectations.","Price changes often reflect revisions to future expectations."),
      S("Risk has more than one face",6,"Identify several ways an investment outcome can disappoint.",[
        "Risk means uncertainty about outcomes, including losing money. Company risk comes from competition, debt, management, or failed products. Market risk affects many assets together. Inflation can reduce purchasing power. Liquidity risk appears when selling quickly is difficult or costly.",
        "Risk and volatility are related but not identical. Volatility describes how widely prices move; risk asks what can prevent the investor from reaching a goal. A stable-looking asset can still carry inflation, credit, or fraud risk."
      ],[K("risk","The possibility that an outcome differs from what was hoped for, including loss."),K("volatility","The degree and frequency of price movement."),K("liquidity risk","The risk that selling quickly will be difficult or costly.")],"Ask what could go wrong, how severe it could be, and whether the goal can recover.","Two kinds of loss","A stock may drop 20% in price. Cash may keep the same dollar balance while inflation reduces what it buys. Both can hurt a goal differently.","Risk includes price changes, business failure, inflation, liquidity, and more."),
      S("Capacity and tolerance are different",6,"Separate the ability to bear loss from the feeling of bearing it.",[
        "Risk tolerance is a person's willingness to accept uncertainty and loss. Risk capacity is the financial ability to absorb loss without derailing essential goals. Someone may feel brave but need the money next year; their capacity is limited. Another person may have decades but still lose sleep during declines.",
        "A sound plan respects both. It does not use a personality quiz as a substitute for cash needs, debt, time horizon, and responsibilities. Revisit the plan when life or goals change."
      ],[K("risk tolerance","A person's willingness to accept investment uncertainty and loss."),K("risk capacity","A person's financial ability to withstand loss."),K("loss","A decrease in value or money received below the amount invested.")],"Willingness cannot create financial capacity.","Brave but short on time","Jordan is comfortable with market swings but needs tuition in 18 months. His confidence does not give the money time to recover from a decline.","A plan must fit both emotional tolerance and financial capacity.")
    ],[
      Q("d3q1","price","What is a market price?","The amount at which a buyer and seller agree to trade","A company's guaranteed true value","The price set forever by an exchange","Prices are momentary market agreements.",1),
      Q("d3q2","expectations","Why might a stock fall after sales rise?","Results may be weaker than expected or costs may worry investors","Rising sales always force prices down","The company stopped existing","Prices respond to expectations as well as reported facts.",2),
      Q("d3q3","risk","Which is an example of inflation risk?","Money buys less as prices rise","A broker forgets a password","A stock pays a dividend","Inflation can erode purchasing power.",0),
      Q("d3q4","volatility","What does volatility describe?","How widely and often a price moves","Whether an investment is insured","A guaranteed chance of loss","Volatility measures price movement, not every dimension of risk.",1),
      Q("d3q5","capacity","What is risk capacity?","The financial ability to withstand loss","Excitement about a popular stock","The number of trades allowed","Capacity depends on finances and goals.",2)
    ],["Market prices are negotiated snapshots.","Expectations and surprises can move prices.","Risk tolerance and risk capacity must both fit the plan."]);

  const day4 = lesson(4,"Bonds: lending instead of owning",24,["Explain a bond as debt.","Connect interest rates, credit risk, and bond prices.","Distinguish individual bonds from bond funds."],[
    S("A bond begins with a loan",6,"Explain the issuer-investor relationship in a bond.",["A bond generally represents money lent to a government, company, or other issuer. The issuer promises payments under stated terms. Unlike stock, a bond does not ordinarily make the investor an owner of the issuer.","The bond's principal, interest terms, and maturity define the basic contract. Bonds vary widely; reading the actual terms matters more than relying on the word 'bond.'"],[K("bond","A debt security representing money lent to an issuer."),K("issuer","The organization that creates and sells a security."),K("principal","The amount the issuer promises to repay under the bond's terms.")],"Stock is ownership; a bond is generally a lending relationship.","City library bond","A city issues bonds to finance a library. Buyers lend the city money and receive the stated payment rights; they do not own a room in the library.","A bond is a contract with payment terms, not a piece of ownership."),
    S("Coupons and maturity",6,"Identify a bond's scheduled cash flows.",["Many bonds pay interest, sometimes called a coupon, on a schedule and return principal at maturity. A zero-coupon bond works differently, so never assume every bond pays current income.","Maturity is the date the principal is due, subject to the issuer's ability and legal obligations. A longer maturity can expose the price to more interest-rate change and uncertainty."],[K("coupon","A bond's stated interest payment."),K("maturity","The date principal is scheduled to be repaid."),K("yield","A measure of return that relates payments to price.")],"Payment terms tell you what is promised; credit quality tells you how uncertain that promise is.","A $1,000 bond","A bond may promise $40 a year and $1,000 at maturity. That promise is valuable only if the issuer can and does meet it.","Coupon, principal, and maturity describe the bond's promised payments."),
    S("Why bond prices move",6,"Explain the inverse relationship between market rates and existing fixed-rate bond prices.",["If new bonds begin offering higher rates, an older fixed-rate bond may be less attractive unless its market price falls. If new rates fall, an older higher-rate bond may become more attractive. This is why a bond can lose value before maturity even when its payments are fixed.","Selling before maturity exposes the investor to the current market price. Holding to maturity may reduce that particular concern, but credit, inflation, call, and reinvestment risks remain."],[K("interest-rate risk","The risk that rate changes reduce a bond's market value."),K("credit risk","The risk that an issuer will not make promised payments."),K("default","Failure to make a required debt payment.")],"Fixed payments do not mean a fixed market price.","Old 3%, new 5%","If new comparable bonds pay 5%, few buyers will pay full price for an old 3% bond. Its price generally must fall to compete.","Bond values respond to rates, credit quality, time, and contract terms."),
    S("Individual bonds and bond funds",6,"Distinguish owning one debt contract from owning shares of a pooled portfolio.",["An individual bond has its own issuer, maturity, and payment terms. A bond fund pools money to own many bonds. The fund can diversify issuer exposure and simplify management, but its share price and income change with its portfolio.","A bond fund does not promise to return your original purchase amount on a personal maturity date. Read its objective, duration, credit quality, fees, and holdings before assuming it behaves like one bond."],[K("bond fund","A pooled investment that primarily holds bonds."),K("duration","A measure commonly used to estimate sensitivity to interest-rate changes."),K("portfolio","A collection of investments.")],"A bond fund is a portfolio product, not one bond with one maturity.","Two different statements","'My bond matures in 2032' can describe one security. 'My bond fund matures in 2032' is usually incorrect because the fund continually holds a portfolio.","Know whether you own a contract or shares of a managed pool.")
  ],[
    Q("d4q1","bond","What does a bond generally represent?","Money lent to an issuer","Ownership of the issuer","A guaranteed profit","Bonds are debt instruments.",1),Q("d4q2","maturity","What is maturity?","The date principal is scheduled to be repaid","The bond's daily price","The issuer's founding date","Maturity is part of the payment contract.",2),Q("d4q3","rates","When new comparable rates rise, what often happens to an older fixed-rate bond's price?","It falls","It is guaranteed to rise","It cannot change","The older lower payment becomes less competitive.",0),Q("d4q4","credit","What is credit risk?","The possibility the issuer will not make promised payments","The number of owners voting","A guarantee from the exchange","A bond promise depends on the issuer.",1),Q("d4q5","fund","How is a bond fund different from one bond?","It holds a changing portfolio and has no personal maturity promise","It cannot lose money","It is company ownership","A fund share represents a pool of bonds.",2)
  ],["Bonds generally represent lending, not ownership.","Fixed payments do not create a fixed market price.","A bond fund is not the same as one bond."]);

  const day5 = lesson(5,"Funds: owning a collection",24,["Explain pooled investing.","Compare mutual funds and ETFs.","Read a fund objective, holdings, and costs."],[
    S("Many investors, one portfolio",6,"Explain how a fund pools money and divides ownership.",["A fund collects money from many investors and buys a portfolio according to a stated objective. Each investor owns shares of the fund, while the fund owns the underlying stocks, bonds, or other assets.","Pooling can make broad ownership practical, but the word 'fund' does not guarantee diversification, low fees, or safety. A narrowly focused fund can hold one industry, region, or strategy."],[K("fund","An investment company or pool that holds a portfolio."),K("portfolio","The investments held by a person or fund."),K("fund share","A unit of ownership in a pooled portfolio.")],"A fund is a container; its holdings and rules determine what is inside.","One share, 500 companies","A broad stock fund may let an investor own a small interest in hundreds of companies through one fund share.","Owning a fund means owning part of its portfolio results."),
    S("Mutual fund mechanics",6,"Describe how mutual-fund shares are generally purchased and priced.",["A mutual fund is an SEC-registered open-end investment company. Investors generally buy from and redeem shares with the fund, directly or through an intermediary, at the next calculated net asset value after an order is received.","Net asset value reflects the value of portfolio assets minus liabilities, divided by fund shares. Sales loads, redemption fees, and operating expenses may also matter."],[K("mutual fund","An open-end pooled investment whose shares are generally bought from and redeemed with the fund."),K("net asset value","Portfolio assets minus liabilities, divided by shares."),K("redemption","Selling mutual-fund shares back to the fund.")],"Mutual funds generally transact at the next calculated NAV, not a continuously changing exchange quote.","Order at noon","An investor orders a mutual fund at noon but does not lock in the prior night's NAV. The order receives the next price calculated under the fund's procedures.","Mutual-fund pricing and trading differ from stock trading."),
    S("ETF mechanics",6,"Describe how ETF shares usually trade.",["An exchange-traded fund also holds a portfolio, but retail investors generally buy and sell ETF shares on an exchange at market prices throughout the trading day. The market price may be slightly above or below the fund's net asset value.","ETFs can be broad, narrow, simple, leveraged, or complex. The label describes a trading structure, not a risk level or investment quality."],[K("ETF","An exchange-traded fund whose shares generally trade on an exchange."),K("premium","A market price above net asset value."),K("discount","A market price below net asset value.")],"ETF shares trade like stocks, but their economic exposure comes from the underlying portfolio.","Price versus NAV","An ETF's holdings are worth $50 per share while buyers trade it at $50.10. The ten-cent difference is a small premium.","An ETF combines a pooled portfolio with exchange trading."),
    S("Read the label and the ingredients",6,"Evaluate a fund using objective, strategy, holdings, risks, and costs.",["Begin with the fund's investment objective and strategy. Then inspect top holdings, concentration, asset types, benchmark, turnover, and principal risks. A name such as 'income' or 'growth' is not enough.","Read the prospectus and fee table. Compare similar funds on the same basis. Past performance shows history, not what must happen next."],[K("prospectus","A legal disclosure document describing an investment's objectives, risks, costs, and operations."),K("expense ratio","Annual fund operating expenses expressed as a percentage of assets."),K("benchmark","A reference index used for comparison.")],"A fund's name is a clue; its disclosures are the evidence.","Two technology funds","One holds 300 global companies; another holds 25 start-ups and uses leverage. Similar names can hide very different risks.","Read what a fund owns, how it operates, and what it costs.")
  ],[
    Q("d5q1","pool","What does a fund investor own?","Shares of a fund that owns a portfolio","A guaranteed portion of every company's cash","One physical asset from the fund","A fund share participates in portfolio results.",1),Q("d5q2","mutual","How are mutual funds generally priced for retail orders?","At the next calculated NAV","At a price fixed for ten years","Only by auction once a month","Mutual funds generally use forward pricing.",2),Q("d5q3","etf","Where do ETF shares generally trade?","On an exchange during the trading day","Only at a bank teller","Directly with each underlying company","ETFs trade at market prices.",0),Q("d5q4","narrow","Does one fund automatically provide broad diversification?","No; a fund may be narrowly concentrated","Yes; every fund owns every market","Yes; the word fund guarantees safety","Holdings determine diversification.",1),Q("d5q5","read","What should you read beyond a fund's name?","Objective, holdings, risks, and costs","Only social-media comments","Only last year's return","Disclosures explain the actual product.",2)
  ],["Funds pool investors' money into portfolios.","Mutual funds and ETFs trade differently.","A fund's holdings, risks, and fees matter more than its name."]);

  const day6 = lesson(6,"Diversification and spreading risk",24,["Explain diversification across and within asset classes.","Identify concentration and overlap.","State what diversification cannot do."],[
    S("Do not depend on one outcome",6,"Explain the purpose of diversification.",["Diversification spreads exposure among investments so one failure has less power over the whole portfolio. It can involve different companies, industries, issuers, regions, and asset classes.","The goal is not to own the most things. It is to avoid accidental dependence on the same source of risk. Ten companies in one fragile industry may be less diversified than a smaller set with genuinely different drivers."],[K("diversification","Spreading investments to reduce dependence on any single exposure."),K("concentration","A large dependence on one investment or risk source."),K("exposure","The amount affected by a particular investment or risk.")],"Count distinct risks, not ticker symbols.","The employer-stock problem","If salary and investments both depend heavily on one employer, job loss and portfolio loss could arrive together.","Diversification reduces the impact of a single disappointment."),
    S("Across asset classes",6,"Describe asset allocation as a portfolio-level decision.",["Asset allocation divides a portfolio among categories such as stocks, bonds, and cash. Each has different patterns of return, volatility, income, and liquidity. The appropriate mix depends on goals, time horizon, risk capacity, and tolerance.","Allocation is not a one-time prediction of the winning category. It is a planned balance of growth, stability, income, and access needs."],[K("asset allocation","Dividing investments among asset classes such as stocks, bonds, and cash."),K("asset class","A category of investments with shared features."),K("cash equivalent","A highly liquid, generally short-term holding.")],"Asset allocation sets the portfolio's major risk structure.","A distant goal and a near bill","Retirement decades away may hold more growth assets; next year's tuition generally needs more stability and liquidity.","The mix should reflect the goal, not the latest winner."),
    S("Within an asset class",6,"Find hidden overlap inside stocks, bonds, or funds.",["Diversifying within stocks can mean multiple companies, sizes, industries, and regions. Within bonds, it can mean different issuers, maturities, and credit quality. Funds can help, but several funds may own the same top companies.","Look through fund labels to holdings. Three different funds can create false diversification if their portfolios overlap heavily."],[K("overlap","The same holdings or risk exposures appearing in multiple investments."),K("sector","A group of companies in a similar part of the economy."),K("issuer diversification","Spreading lending exposure among different borrowers.")],"Different names do not guarantee different risks.","Three funds, same companies","A broad index fund, a growth fund, and a technology fund may all hold the same large technology companies. The portfolio is more concentrated than the fund count suggests.","Inspect underlying holdings and exposures."),
    S("What diversification cannot promise",6,"State the limits of diversification.",["Diversification cannot guarantee a profit or prevent loss when broad markets fall. It also cannot repair fraud, excessive fees, a mismatched time horizon, or risks hidden inside a complex product.","Its benefit is resilience: fewer single points of failure and a better chance that different holdings respond differently. Rebalancing can restore a chosen allocation after market movement, but may create taxes or transaction costs depending on the account."],[K("systematic risk","Broad market risk that diversification cannot fully remove."),K("rebalancing","Restoring a portfolio toward its intended allocation."),K("correlation","The degree to which investments move together.")],"Diversification manages risk; it does not erase risk.","A broad market decline","Many diversified holdings may fall together in a crisis. Diversification can still reduce company-specific damage, but it cannot make the portfolio immune.","Use diversification as risk control, never as a guarantee.")
  ],[
    Q("d6q1","purpose","What is diversification designed to reduce?","Dependence on one investment or risk source","Every possible loss","The need to understand holdings","Diversification limits concentration.",1),Q("d6q2","allocation","What is asset allocation?","Dividing a portfolio among asset classes","Buying only the recent winner","Holding many accounts with the same asset","Allocation determines the broad mix.",2),Q("d6q3","overlap","Why inspect fund holdings?","Different funds may own many of the same investments","Every fund lies about its name","Funds cannot hold stocks","Overlap can create hidden concentration.",0),Q("d6q4","limit","What can diversification guarantee?","Nothing; it cannot guarantee profit or prevent all loss","A positive return every year","No price changes","Diversification is risk management, not insurance.",1),Q("d6q5","rebalance","What is rebalancing?","Returning toward a planned allocation","Predicting tomorrow's top stock","Eliminating taxes","Market moves can shift a portfolio away from its plan.",2)
  ],["Diversification spreads distinct sources of risk.","Asset allocation sets the broad portfolio mix.","Diversification cannot guarantee gains or prevent every loss."]);

  const day7 = lesson(7,"A calm first-week review",22,["Connect goals, ownership, debt, funds, and diversification.","Correct common misconceptions.","Explain the first-week model aloud."],[
    S("Start with the goal",5,"Reconstruct the decision sequence from goal to product.",["A sound sequence begins with the goal, amount, time horizon, access needs, and capacity for loss. Only then should the learner compare saving, stocks, bonds, or funds.","Starting with a product invites chasing. Starting with the goal creates a reasoned filter."],[K("goal-first planning","Choosing financial tools only after defining the goal and constraints."),K("constraint","A limit such as time, access, or ability to bear loss.")],"The goal is the assignment; the product is a tool.","Reverse the advertisement","When an ad says 'buy this fund,' ask which goal, horizon, risks, and costs it actually fits.","Goals and constraints come before product names."),
    S("Ownership, lending, and pooling",6,"Compare stocks, bonds, and funds in one framework.",["A stock generally represents company ownership. A bond generally represents lending to an issuer. A fund is a container that may hold stocks, bonds, or other assets.","These categories answer different questions. 'Is it a fund?' describes structure; 'what does it own?' describes exposure. A stock fund and bond fund are both funds but carry different underlying risks."],[K("ownership claim","An interest in a company's results and value."),K("debt claim","A contractual right to payments from a borrower."),K("pooled investment","A vehicle combining money from many investors.")],"Separate the wrapper from what is inside.","ETF is not an asset class","An ETF may hold stocks, bonds, commodities, or a narrow strategy. Saying 'I own an ETF' does not explain the economic exposure.","Stock, bond, and fund are connected but not interchangeable."),
    S("Prices, risk, and time",6,"Connect market movement to the investor's horizon.",["Prices respond to trading, expectations, rates, and uncertainty. A decline is not automatically proof that a business is worthless, but it can expose a plan that took too much risk for its deadline.","Time does not guarantee recovery. It can increase capacity to wait through temporary volatility, while diversification can reduce dependence on a single outcome."],[K("drawdown","A decline from an investment or portfolio's prior peak."),K("recovery period","The time required to regain an earlier value."),K("deadline risk","The danger that a loss occurs when money must be used.")],"Risk becomes personal when market timing collides with a goal date.","Tuition during a downturn","A diversified stock portfolio may be reasonable for a distant goal but still wrong for tuition due next semester.","Match the risk of the assets to the timing of the goal."),
    S("Teach the model",5,"Deliver a short, accurate explanation of the week's ideas.",["Try this sequence without notes: saving protects near-term needs; investing accepts uncertainty for possible return; stocks are ownership; bonds are lending; funds pool assets; diversification spreads risk.","If one sentence feels fuzzy, return to that lesson. Retrieval—bringing an idea back from memory—strengthens learning more than rereading alone."],[K("retrieval practice","Strengthening memory by recalling information without looking."),K("mental model","A connected explanation of how ideas fit together.")],"Being able to explain the connections matters more than memorizing isolated words.","The 60-second lesson","Explain the six-part sequence to another person, then invite them to ask one question you cannot answer yet.","Clear explanation reveals both learning and the next question.")
  ],[
    Q("d7q1","sequence","What should come first?","Define the goal and constraints","Choose the hottest product","Predict next week's market","Planning begins with the purpose.",1),Q("d7q2","stock","A stock generally represents what?","Ownership in a company","A loan to a government","A guaranteed payment","Stock is equity ownership.",2),Q("d7q3","bond","A bond generally represents what?","A lending relationship","Physical company property","An insurance policy","Bonds are debt instruments.",0),Q("d7q4","fund","What does the word fund tell you?","Money is pooled into a portfolio; holdings still matter","The investment is safe","It owns only stocks","A fund is a structure, not one risk level.",1),Q("d7q5","diversify","What does diversification do?","Reduces dependence on a single exposure","Guarantees a profit","Makes the goal irrelevant","Diversification manages concentration.",2)
  ],["Plan from the goal outward.","Stock is ownership; bond is lending; fund is a pool.","Diversification and time help manage risk but make no guarantees."]);

  const day8 = lesson(8,"Returns, time, and compounding",24,["Calculate a simple holding-period return.","Explain compound growth and compound loss.","Use assumptions without turning them into promises."],[
    S("Return includes more than price",6,"Identify the components of investment return.",["Total return combines price change with income such as interest or dividends, then accounts for relevant costs. A stock that rises $5 and pays $1 produced more than price change alone; taxes may also affect what the investor keeps.","Returns should be compared over the same time period and with the same assumptions. A one-month percentage and a ten-year average are not directly comparable."],[K("total return","Price change plus income, adjusted for relevant costs."),K("capital gain","An increase in value realized when an asset is sold."),K("income return","Return received through payments such as interest or dividends.")],"Measure the whole result over a clearly stated period.","From $100 to $106","A $100 investment ends at $104 and pays $2. Before fees and taxes, total return is $6, or 6%.","Return needs a beginning value, ending value, cash flows, and period."),
    S("Growth can build on growth",6,"Explain compounding in plain language.",["Compounding occurs when returns remain invested and later returns apply to both the original money and earlier growth. The effect depends on time, rate, contributions, fees, taxes, and market results.","Compound growth is powerful but not automatic. Investments can have negative periods, and projections are illustrations—not guarantees."],[K("compounding","Returns generating additional returns over time."),K("reinvestment","Using income or gains to acquire more of an investment."),K("principal","The original amount placed into an account or investment.")],"Time gives compounding more opportunities, but actual returns remain uncertain.","Two 10% periods","$100 growing 10% becomes $110; another 10% becomes $121, because the second period applies to $110.","Compounding builds on the current balance, not only the starting amount."),
    S("Losses compound too",6,"Calculate why equal percentage gains and losses do not cancel.",["A 50% decline followed by a 50% gain does not return an account to its starting value. The gain applies to the smaller balance. After large losses, a larger percentage gain is required to recover.","This asymmetry is one reason risk control matters. Avoiding catastrophic loss can be more important than chasing the highest possible return."],[K("percentage loss","A decline measured relative to the starting value."),K("break-even","The point at which value returns to its starting level."),K("sequence of returns","The order in which gains and losses occur.")],"Percentages always apply to the current base.","Down 50, up 50","$100 falls 50% to $50. A 50% gain adds $25, producing $75—not $100.","Equal percentage losses and gains do not cancel when the base changes."),
    S("Use projections honestly",6,"Distinguish an illustration from a forecast or promise.",["A compound-growth calculator can show how contributions, time, and an assumed rate interact. Change the rate or timing and the result changes. Real markets do not deliver smooth returns every year.","Use a range of conservative assumptions, include fees, and label every projection. Do not present historical averages as guaranteed future results."],[K("projection","An estimate based on stated assumptions."),K("assumption","An input treated as true for an analysis."),K("annualized return","A return expressed as an average yearly rate under a specified method.")],"A projection is a planning tool, not a prediction.","Three scenarios","Compare 3%, 5%, and 7% assumptions rather than treating 7% as certain. Notice how fees and starting later change each result.","Make assumptions visible and test more than one outcome.")
  ],[
    Q("d8q1","return","What can total return include?","Price change and income, less relevant costs","Only the current price","Only dividends","Total return measures the whole investment result.",1),Q("d8q2","compound","What is compounding?","Returns potentially earning later returns","A guarantee of profit","Paying every return out as cash","Reinvested growth changes the future base.",2),Q("d8q3","loss","After $100 falls 50% then rises 50%, what is it worth?","$75","$100","$125","The second percentage applies to $50.",0),Q("d8q4","projection","What is a projection?","An estimate based on assumptions","A promised outcome","A regulator's guarantee","Assumptions must be visible.",1),Q("d8q5","compare","How should returns be compared?","Using consistent periods and assumptions","By comparing any two percentages","Using only the best year","Consistent measurement prevents misleading comparisons.",2)
  ],["Total return includes price and income.","Compounding can magnify both growth and the effect of losses.","Projections depend on assumptions and never guarantee results."]);

  const day9 = lesson(9,"Fees and why small costs matter",24,["Identify common investment costs.","Explain how fees reduce compounding.","Compare costs in dollars as well as percentages."],[
    S("Every dollar charged stops working",6,"Explain the direct and compounding effect of a fee.",["Fees reduce the amount remaining in an account. The cost is not only today's deduction; the removed money also cannot earn future returns. Over long periods, small annual differences can create large dollar gaps.","A low fee does not make a poor investment good, and a high fee is not automatically unlawful. Costs must be evaluated alongside services, strategy, risk, and alternatives."],[K("fee","An amount charged for a service, account, or investment."),K("expense ratio","Annual fund operating expenses stated as a percentage of assets."),K("net return","Return remaining after costs.")],"Costs are certain deductions from uncertain returns.","One percentage point","On $10,000, a 1% annual fee begins near $100 per year. The long-run cost can exceed the sum of visible charges because lost growth compounds.","Judge fees by both current dollars and future effect."),
    S("Know the fee vocabulary",6,"Locate transaction, account, advisory, and fund costs.",["A commission can apply to a transaction. A spread is the gap between bid and ask. Funds have operating expenses and may have sales loads or other charges. Advisers may charge a percentage of assets, a flat fee, hourly fee, or another arrangement.","'Zero commission' does not mean zero cost. Spreads, fund expenses, options charges, account fees, interest, and payment practices may still matter."],[K("commission","A charge associated with buying or selling."),K("bid-ask spread","The difference between the highest bid and lowest ask."),K("assets-under-management fee","A charge calculated as a percentage of managed assets.")],"Ask for the complete cost picture, not one advertised price.","The free trade","A trade has no commission, but the investment has a 0.80% expense ratio and a wide spread. The transaction is not costless.","Different layers of cost can appear in one account."),
    S("Compare like with like",6,"Translate percentages into estimated dollars.",["Compare similar products at the same investment amount and holding period. A fee table in a prospectus can show standardized examples. FINRA's Fund Analyzer and other official tools can help illustrate cumulative cost.","Services also matter. Advice, planning, tax work, or specialized management may have value, but the investor should understand what is received, conflicts, and less costly alternatives."],[K("fee table","A standardized disclosure of an investment's costs."),K("sales load","A sales charge on certain fund purchases or redemptions."),K("turnover","How frequently a fund buys and sells portfolio holdings.")],"A percentage becomes understandable when converted to dollars and tied to services.","0.10% versus 1.00%","On the same balance, 1.00% is ten times 0.10%. The exact dollar gap changes as the balance changes.","Use equal assumptions and inspect every layer of cost."),
    S("Ask the cost questions",6,"Use a repeatable checklist before agreeing to a product or service.",["Ask: What will I pay to buy, hold, receive advice on, and sell this? Are there penalties or surrender charges? Does the person receive compensation from a provider? Where are the costs disclosed in writing?", "Then ask how the fee changes if the account grows or shrinks. Keep copies of disclosures and review statements for unexpected charges."],[K("conflict of interest","A situation in which compensation or another interest could influence a recommendation."),K("surrender charge","A fee for exiting certain products during a stated period."),K("Form CRS","A relationship summary describing services, fees, conflicts, and disciplinary history.")],"If a cost cannot be explained plainly, pause before proceeding.","One-sentence test","Ask the professional to state the first-year dollar cost on your expected balance and identify every payment they or their firm may receive.","Clear written cost answers are part of informed consent.")
  ],[
    Q("d9q1","effect","Why do annual fees have a compounding effect?","Removed money cannot earn later returns","Fees guarantee higher performance","Fees are refunded automatically","Costs reduce both balance and possible future growth.",1),Q("d9q2","zero","Does zero commission mean zero cost?","No; spreads, fund, and account costs may remain","Yes; no other cost can exist","Yes; the government pays every fee","Look beyond one advertised charge.",2),Q("d9q3","ratio","What is an expense ratio?","Annual fund operating expenses as a percentage of assets","A guaranteed return","A broker's phone number","It is one layer of fund cost.",0),Q("d9q4","compare","How should fees be compared?","With the same amount, period, services, and assumptions","By choosing the longest document","Using only percentages without dollars","Like-for-like comparison is meaningful.",1),Q("d9q5","ask","What should an investor request?","Written disclosure of all costs and compensation","A verbal promise of no risk","Only last month's performance","Written details support informed decisions.",2)
  ],["Fees reduce the money left to compound.","Zero commission is not the same as zero cost.","Compare total costs in both percentages and dollars."]);

  const day10 = lesson(10,"Brokerage accounts and order basics",25,["Explain what a brokerage account does.","Compare market and limit orders.","Recognize account and trading risks."],[
    S("The brokerage account is the container",6,"Describe the brokerage firm's role and account ownership.",["A brokerage account can hold cash and investments and lets a customer place orders. The brokerage firm maintains records, provides statements, and routes orders. It is not the operating company whose shares are purchased.","Before opening an account, review services, fees, investment choices, minimums, data practices, and how to contact support. Confirm the firm and professional through official registration tools."],[K("brokerage account","An account used to hold investments and place orders through a brokerage firm."),K("brokerage firm","A firm that carries customer accounts and handles securities transactions."),K("custody","Safekeeping and recordkeeping for financial assets.")],"The brokerage is an intermediary and recordkeeper, not a guarantor of investment performance.","Three separate companies","A customer uses Broker A to buy shares of Company B that trade on Exchange C. Each has a different job.","Know who holds the account, what you own, and where orders may execute."),
    S("Cash and margin",6,"Distinguish paying in full from borrowing through the account.",["In a cash account, the customer generally pays in full for purchases. A margin account allows borrowing from the broker, using account assets as collateral, under specific rules and interest charges.","Margin magnifies both gains and losses. The firm may require additional funds or sell assets without consulting the customer when equity falls below requirements. Beginners should not treat margin as ordinary cash."],[K("cash account","A brokerage account in which purchases are generally paid in full."),K("margin account","An account that permits borrowing from the brokerage firm."),K("margin call","A demand to add funds or securities after account equity falls.")],"Borrowing to invest creates risks beyond the investment itself.","A 20% decline with borrowing","If half a purchase is borrowed, a 20% asset decline can create a much larger percentage loss on the investor's own money, before interest.","Read whether the application opens cash, margin, or both."),
    S("Market and limit orders",7,"Choose an order type based on execution versus price control.",["A market order seeks prompt execution but does not guarantee the execution price. In a fast or thin market, the final price can differ from the last quote.","A limit order sets a maximum purchase price or minimum sale price. It gives price control but may never execute. Order duration and partial fills also matter."],[K("market order","An order seeking prompt execution at the best available price."),K("limit order","An order to trade only at a specified price or better."),K("execution","Completion of a buy or sell order.")],"Market orders emphasize execution; limit orders emphasize price boundaries.","Buying with a $20 limit","A buy limit at $20 can fill at $20 or less. If sellers remain above $20, it does not execute.","No order type guarantees both immediate execution and a particular price."),
    S("Pause before pressing submit",6,"Use an order-review checklist.",["Confirm the ticker, investment name, buy or sell direction, quantity, order type, limit price if any, time in force, estimated cost, and account. Similar ticker symbols and accidental extra zeros cause real errors.","After submission, check order status and later confirm execution. A cancellation request is not effective until confirmed. Review statements and trade confirmations for discrepancies."],[K("ticker symbol","A short code used to identify a traded security."),K("time in force","Instructions for how long an order remains active."),K("trade confirmation","A record of the terms of an executed transaction.")],"The final review is part of the investment decision.","The ten-second check","Read the full investment name, action, share count, order type, and estimated dollars aloud before submitting.","Verify before, monitor during, and confirm after an order.")
  ],[
    Q("d10q1","broker","What does a brokerage firm do?","Maintains accounts and handles customer orders","Guarantees every investment","Operates every company purchased","The broker is an intermediary.",1),Q("d10q2","margin","What makes margin risky?","It uses borrowing and can magnify loss","It prevents all selling","It removes interest charges","Borrowing adds leverage and obligations.",2),Q("d10q3","market","What does a market order prioritize?","Prompt execution, not a guaranteed price","A precise guaranteed price","Avoiding all fees","Market conditions determine execution price.",0),Q("d10q4","limit","What can happen to a limit order?","It may not execute","It must fill immediately","It becomes a savings account","Price control comes with execution uncertainty.",1),Q("d10q5","review","What should be checked before submitting?","Security, direction, quantity, order type, and estimated cost","Only the logo color","Only yesterday's price","Order details prevent avoidable mistakes.",2)
  ],["A brokerage account holds assets and routes orders.","Margin borrowing can magnify losses.","Market and limit orders make different trade-offs."]);

  const day11 = lesson(11,"Reading information without chasing hype",24,["Separate evidence from commentary.","Read company and fund disclosures.","Recognize performance and headline traps."],[
    S("Build a source ladder",6,"Rank sources by their proximity to verifiable facts.",["Start with primary materials: regulatory filings, audited statements, prospectuses, and official announcements. Then use reputable analysis to add context. Social posts and promotional clips may suggest questions but should not be the sole evidence for a decision.","A primary source can still contain management estimates or marketing language. Read what is claimed, what period it covers, and what limitations are disclosed."],[K("primary source","An original filing, disclosure, data release, or direct record."),K("secondary source","Analysis or reporting based on other sources."),K("evidence","Information that supports or challenges a claim.")],"Move closer to the original evidence before believing a strong claim.","The viral revenue chart","A post shows record revenue. The filing reveals losses grew faster and share count increased. The fuller source changes the interpretation.","Use commentary to find questions and primary sources to investigate them."),
    S("Read a company in layers",6,"Locate business, risk, financial, and management information.",["A public company's Form 10-K describes the business, risk factors, audited financial statements, and management discussion. Form 10-Q provides quarterly updates, and Form 8-K reports specified material events.","One number rarely tells the story. Compare revenue, expenses, cash flow, debt, share count, and relevant business measures across periods. Read footnotes and risk disclosures."],[K("Form 10-K","A public company's annual SEC report."),K("Form 10-Q","A public company's quarterly SEC report."),K("Form 8-K","A report of specified material company events.")],"Financial statements gain meaning when read with the business model, notes, and risks.","Profit without cash","A company reports accounting profit but negative operating cash flow. The difference deserves investigation, not an instant conclusion.","Read trends and relationships, not isolated numbers."),
    S("Read a fund in layers",6,"Use a prospectus and shareholder report to understand a fund.",["A fund prospectus explains objective, strategy, principal risks, fees, purchase and sale information, and management. Shareholder reports provide performance and portfolio information.","Check benchmark choice, holdings, turnover, concentration, and whether performance shown is before or after costs. Confirm that the comparison period is appropriate."],[K("shareholder report","A periodic fund report with performance and portfolio information."),K("principal risk","A major risk identified in an investment's disclosure."),K("turnover rate","A measure of portfolio trading activity.")],"The fund's disclosures explain the investment you actually own.","A high-return fund","The prospectus reveals the fund is leveraged and narrowly concentrated. Its high return came with risks hidden by the headline.","Performance makes sense only beside strategy, risk, and cost."),
    S("Slow down the headline",6,"Identify common persuasion and performance traps.",["Watch for cherry-picked dates, percentages without base amounts, survivorship bias, unnamed sources, testimonials, and comparisons to an unsuitable benchmark. 'Up 200%' does not tell you how likely, repeatable, or risky the result was.","Use a waiting rule for emotionally charged claims. Write the claim in neutral words, list evidence for and against it, and identify what would prove it wrong."],[K("cherry-picking","Selecting only favorable data while ignoring relevant contrary evidence."),K("survivorship bias","Focusing on successes while missing failures that disappeared."),K("benchmark mismatch","Comparing results with an inappropriate reference.")],"Urgency and excitement are signals to improve the process, not speed it up.","Translate the boast","'This stock cannot miss' becomes 'The promoter predicts a gain but has not shown a guarantee, complete risks, or independent evidence.'", "Neutral language makes weak reasoning easier to see.")
  ],[
    Q("d11q1","source","Which is closest to a primary source?","A company's SEC filing","An anonymous repost","A celebrity reaction","Original disclosures provide direct evidence.",1),Q("d11q2","10k","What does Form 10-K provide?","Annual business, risk, and audited financial information","A guaranteed stock target","A broker's personal budget","It is a core annual company filing.",2),Q("d11q3","fund","Where can principal fund risks and fees be found?","The prospectus","Only the ticker symbol","A testimonial","The prospectus contains required disclosures.",0),Q("d11q4","cherry","What is cherry-picking?","Showing favorable data while omitting relevant contrary data","Comparing equal periods","Reading footnotes","Selective evidence can mislead.",1),Q("d11q5","hype","What should urgency trigger?","A pause and verification process","An immediate purchase","A larger borrowed position","Emotion is a reason to slow down.",2)
  ],["Climb from promotion toward primary evidence.","Read business, risks, statements, notes, and trends together.","Translate hype into neutral, testable claims."]);

  const day12 = lesson(12,"Fraud warning signs and safer questions",25,["Recognize classic fraud red flags.","Verify people and investments independently.","Respond safely to suspected fraud."],[
    S("Promises that should stop you",6,"Recognize combinations of return, guarantee, secrecy, and urgency.",["Classic warning signs include guaranteed high returns, little or no risk, pressure to act immediately, secrecy, vague explanations, and returns that seem unusually steady. Every real investment involves risk.","One red flag does not prove fraud, but it justifies stopping. Multiple red flags should make the response stronger—not more curious with money."],[K("investment fraud","Deception used to obtain money through a false investment claim."),K("guaranteed return","A promise of a fixed result; suspicious when paired with risky investments."),K("high-pressure tactic","An attempt to prevent time for independent review.")],"High return, no risk, and act now is a dangerous combination.","The private opportunity","A caller promises 20% with no loss, says regulators would not understand, and needs payment today. Stop; do not send money or documents.","Urgency is never a substitute for verification."),
    S("Verify the person",6,"Check registration and identity through independent channels.",["Use Investor.gov's professional search and FINRA BrokerCheck to research licensing, employment, and disciplinary history. Find contact information independently; do not rely on links or numbers supplied by the person making the pitch.","Registration does not guarantee honesty or suitability, but an unregistered seller or mismatched identity is a major warning. Imposters may copy a real professional's name and credentials."],[K("BrokerCheck","FINRA's free tool for researching brokers and firms."),K("registration","Official authorization or filing status required for certain professionals and offerings."),K("imposter scam","Fraud in which someone pretends to be a legitimate person or firm.")],"Verify both credentials and identity using contact information you find yourself.","Real name, fake caller","A scammer uses a registered adviser's name. Calling the firm's independently verified number reveals the adviser never made the offer.","A real credential can be stolen; confirm the communication channel too."),
    S("Verify the investment",7,"Ask where money goes, what rights exist, and where disclosures are filed.",["Ask how the investment makes money, what could cause loss, how it can be sold, what fees apply, and where written disclosures can be checked. Search SEC EDGAR for relevant company filings and regulator alerts.","Do not rely on testimonials, screenshots, celebrity endorsements, or a polished app balance. Fake platforms may display profits that cannot be withdrawn. Be suspicious of payment by cryptocurrency, gift card, wire to an individual, or an unfamiliar overseas account."],[K("EDGAR","The SEC's public database of company and investment filings."),K("due diligence","Independent investigation before making a decision."),K("withdrawal test","An attempt to confirm funds can actually be retrieved; scammers may still manipulate it.")],"Understand the economic engine and verify the legal trail before sending money.","The fake trading screen","An app shows a $40,000 balance but demands an extra tax payment to release it. Legitimate taxes are not usually paid to a stranger to unlock an account.","A screen is not proof that assets exist."),
    S("If something feels wrong",6,"Protect accounts, preserve evidence, and report promptly.",["Stop communication and payments. Do not pay a recovery service that contacts you unexpectedly; recovery scams often target earlier victims. Contact the financial institution using a verified number, change compromised credentials, and preserve messages, receipts, wallet addresses, and screenshots.","Report concerns to the SEC, FINRA, the FTC, local law enforcement, or the relevant state regulator. Fast reporting may help limit harm, though recovery is not guaranteed. Shame helps scammers; speaking up helps protect people."],[K("recovery scam","A second scam promising to recover lost money for an upfront payment."),K("account takeover","Unauthorized control of an account."),K("incident evidence","Records that can support an investigation, such as messages and payment details.")],"Stop, secure, document, and report.","The second caller","After a loss, someone promises recovery for a fee. Do not pay; contact regulators and institutions through official channels.","A suspected scam is a safety problem, not a personal failure.")
  ],[
    Q("d12q1","redflag","Which combination is a classic warning?","High guaranteed return, no risk, and urgency","Written risks and time to review","Independent registration check","Impossible promises and pressure are fraud signals.",1),Q("d12q2","verify","How should a professional's identity be checked?","Through official tools and independently found contact information","By clicking the pitcher's link","By trusting a profile photo","Imposters can copy legitimate names.",2),Q("d12q3","screen","Does an app balance prove assets exist?","No","Yes, always","Only if the colors look professional","Fake platforms can display invented profits.",0),Q("d12q4","payment","Which payment request is especially suspicious?","Gift card or crypto sent to a stranger","A documented fee to a verified institution","A normal bank transfer into your own account","Unusual irreversible methods are common scam signals.",1),Q("d12q5","response","What should happen after suspected fraud?","Stop, secure accounts, preserve evidence, and report","Pay a recovery caller","Delete every record","Documentation and official reporting are safer steps.",2)
  ],["Guaranteed high return with little risk is a major warning.","Verify the person and the investment independently.","After suspected fraud: stop, secure, document, and report."]);

  const day13 = lesson(13,"Building a personal learning checklist",24,["Create a repeatable research checklist.","Document goals and decision boundaries.","Know when professional help may be useful."],[
    S("Write the decision before the product",6,"Create a one-page decision statement.",["Write the goal, target amount, time horizon, required access, maximum acceptable loss, and what success means. Note which money must not be invested, including emergency and near-term funds.","This statement creates boundaries before advertising, headlines, or fear of missing out can change the question."],[K("decision statement","A written description of the goal, constraints, and success criteria."),K("decision boundary","A rule defining what is outside an acceptable choice."),K("essential funds","Money needed for living costs, emergencies, or near-term obligations.")],"Prewritten boundaries protect decisions from emotional pressure.","The no-invest list","Renee writes: rent, emergency savings, and next year's insurance premium will not be invested in volatile assets.","Define the assignment and protected money in writing."),
    S("Understand what you own",6,"Build a plain-language product test.",["For any investment, be able to explain what it is, how it may earn or lose money, who issues or manages it, how it can be sold, what rights you have, and what could make it fail.","If the explanation requires slogans or cannot fit in a short paragraph, pause. Complexity is not automatically bad, but unexplained complexity is a risk."],[K("investment thesis","A reasoned explanation of why an investment may serve a goal."),K("exit terms","Rules, costs, and practical ability to leave an investment."),K("counterparty","The person or organization on the other side of a financial obligation.")],"Do not buy what you cannot explain in ordinary language.","The neighbor test","Explain the product to a neighbor without using 'safe,' 'can't miss,' or unexplained abbreviations. List three ways it could lose money.","Understanding includes both the return path and the failure path."),
    S("Verify people, costs, and evidence",6,"Combine source, credential, and cost checks.",["Check registration and identity through official tools. Read primary disclosures. List every fee and conflict. Compare at least one simpler or lower-cost alternative on the same assumptions.","Write what evidence would change your mind. A good process welcomes disconfirming information instead of defending the first idea."],[K("disconfirming evidence","Information that challenges an existing belief."),K("alternative","Another option evaluated against the same goal."),K("written disclosure","A document formally describing terms, costs, or risks.")],"A decision process should try to prove itself wrong before money is committed.","The red-team question","Ask: 'What would a skeptical, informed person say I am missing?' Then investigate that point.","Verify independently and compare consistently."),
    S("Know when to ask for help",6,"Identify questions that may require a qualified professional.",["Tax, legal, estate, insurance, debt, and retirement decisions can interact. A qualified professional may help when the stakes or complexity exceed your knowledge. Verify credentials, services, fees, conflicts, and disciplinary history.","Advice is not a substitute for understanding. Ask the professional to explain recommendations, alternatives, costs, risks, and why the choice fits your goal."],[K("fiduciary duty","A legal obligation in specified contexts to act in a client's best interest."),K("scope of service","The work a professional agrees to provide."),K("disciplinary history","Official records of certain complaints, actions, or sanctions.")],"Professional help should make the decision clearer and more accountable.","Five questions for an adviser","What services do you provide? What will I pay? How are you compensated? What conflicts exist? Why does this fit my goal better than alternatives?", "Verify the helper and keep ownership of the decision.")
  ],[
    Q("d13q1","statement","What belongs in a decision statement?","Goal, timeline, access, and loss boundaries","A prediction of the hottest stock","Only an account password","Written constraints guide product selection.",1),Q("d13q2","explain","What should you be able to explain?","How the investment can gain, lose, and be sold","Only its ticker symbol","Why a celebrity likes it","Understanding includes failure paths.",2),Q("d13q3","challenge","What is disconfirming evidence?","Information that challenges your belief","A guaranteed approval","A fee discount","Good research tests the idea.",0),Q("d13q4","compare","How should alternatives be compared?","Against the same goal and assumptions","Using different time periods","Only by their best year","Consistent comparisons reduce bias.",1),Q("d13q5","professional","What should be checked about a professional?","Credentials, services, fees, conflicts, and history","Only clothing style","Only social-media followers","Professional help also requires due diligence.",2)
  ],["Write goals and boundaries before selecting products.","Understand how an investment works and fails.","Verify evidence, costs, alternatives, and professionals."]);

  const day14 = lesson(14,"Review, explain, and choose a next step",25,["Integrate the complete course model.","Demonstrate learning through explanation.","Choose a safe next learning action."],[
    S("The complete map",6,"Connect personal goals to markets without skipping steps.",["The course begins with the household: goals, emergency savings, time, and capacity for loss. It moves to companies and issuers, then to stocks, bonds, funds, prices, diversification, returns, fees, accounts, evidence, and fraud protection.","The sequence matters. A market product is never detached from the person who must live with its risks and use the money for a purpose."],[K("financial plan","A connected approach to goals, resources, risks, and actions."),K("investment plan","Rules connecting investment choices to goals and constraints."),K("course model","The linked concepts used to reason about investing.")],"Investing begins and ends with the real-life goal it is meant to serve.","Trace one dollar","Follow a dollar from income to emergency savings or a long-term account, into a fund, into company stock or issuer debt, and eventually back through a sale or payment.","Personal purpose connects every technical concept."),
    S("Correct the six dangerous sentences",6,"Replace common myths with accurate statements.",["Replace: 'Stocks always go up,' 'Bonds cannot lose,' 'A fund is automatically diversified,' 'More return means better,' 'Zero commission means free,' and 'Registered means guaranteed.'", "Accurate language includes uncertainty, time horizon, underlying holdings, total cost, and independent verification. Precision is a safety skill."],[K("myth","A widely repeated but inaccurate belief."),K("qualification","Language stating the limits or conditions of a claim."),K("guarantee","A legally meaningful promise; most investment outcomes are not guaranteed.")],"Words like always, never, safe, and guaranteed deserve immediate scrutiny.","Rewrite one myth","'Funds are safe' becomes 'A fund's risk depends on its holdings, strategy, leverage, concentration, and costs.'", "Replace slogans with conditions and evidence."),
    S("Teach it back",7,"Give a two-minute explanation of investing foundations.",["Explain: saving versus investing; stock versus bond; individual security versus fund; price versus value; risk tolerance versus capacity; diversification and its limits; fees; order basics; and fraud checks.","Use one worked example and one warning. Teaching reveals gaps and turns vocabulary into a connected model."],[K("teach-back","Explaining an idea in your own words to demonstrate understanding."),K("transfer","Applying learning to a new situation."),K("metacognition","Awareness of what you understand and what still needs work.")],"The ability to explain and apply is stronger evidence than recognition alone.","The family conversation","Explain why a publicly traded share is ownership, why a brokerage app is not the company, and why a rising price is not guaranteed evidence of a good decision.","Clear teaching is the final practice, not a performance."),
    S("Choose the next safe action",6,"Select a learning step that does not require an immediate purchase.",["A next step can be reviewing workplace retirement-plan materials, building emergency savings, reading one prospectus, checking a professional's registration, comparing fees, or writing a goal statement. Learning does not require opening an account tonight.","If you later act, use the checklist: goal, time, access, risk, product, costs, evidence, person, order, and records. Pause whenever an answer is unclear."],[K("next action","A specific, low-risk step that advances a goal."),K("implementation","Putting a reviewed plan into practice."),K("review date","A scheduled time to revisit a plan or decision.")],"The best next step is specific, reversible when possible, and connected to the goal.","A 20-minute next step","Choose one account statement and identify every holding and fee. Write questions; make no trade until the answers are clear.","Completion means being ready to learn and decide more safely—not being pressured to invest.")
  ],[
    Q("d14q1","start","Where should an investing plan begin?","With goals, time, emergency needs, and risk capacity","With a social-media pick","With the most complex product","The household goal frames the plan.",1),Q("d14q2","myth","Which statement is accurate?","A fund's risk depends on its holdings and strategy","Every bond is safe","Registration guarantees profit","Product labels do not remove risk.",2),Q("d14q3","price","What does a rising price prove?","Only that trades occurred at higher prices; it does not guarantee a sound decision","The asset can never fall","Every investor agrees","Price is market information, not a promise.",0),Q("d14q4","fees","Why review fees?","They reduce the return left for the investor","They guarantee expert results","They never compound","Costs are certain deductions.",1),Q("d14q5","next","Which is a safe next step?","Write a goal and review one official disclosure before acting","Borrow immediately to trade","Send money after an urgent pitch","Learning and verification can come before transactions.",2)
  ],["Connect every investment choice to a real goal.","Use precise language, evidence, and total costs.","Finishing the course does not create pressure to buy anything."]);

  const day2 = {...window.IF_LESSON, quiz: window.IF_QUIZ};
  day2.sections = day2.sections.map(section => ({...section, check: section.practice || section.scenario || null}));
  window.IF_LESSONS = [day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11, day12, day13, day14];
})();
