const fs = require("fs");
const path = require("path");
const vm = require("vm");
const root = path.resolve(__dirname, "..");
let failures = 0;
const ok = (condition, message) => { console.log(`${condition ? "PASS" : "FAIL"} ${message}`); if (!condition) failures++; };
const context = {window:{}}; vm.createContext(context);
for (const file of ["content/course.js","content/lesson-day-2.js","content/quiz-day-2.js","content/glossary.js","content/lessons.js"]) vm.runInContext(fs.readFileSync(path.join(root,file),"utf8"),context,{filename:file});
const lessons = context.window.IF_LESSONS;
const index = fs.readFileSync(path.join(root,"index.html"),"utf8");
const app = fs.readFileSync(path.join(root,"assets/js/app.js"),"utf8");
const sw = fs.readFileSync(path.join(root,"service-worker.js"),"utf8");
ok(Array.isArray(lessons) && lessons.length === 14,"exactly 14 complete lessons load");
ok(lessons.map(x=>x.day).join(",") === "1,2,3,4,5,6,7,8,9,10,11,12,13,14","lesson days are ordered 1 through 14");
ok(lessons.every(x=>x.totalMinutes >= 20 && x.totalMinutes <= 30),"each lesson is a 20-30 minute introductory unit");
ok(lessons.every(x=>x.sections.length >= 4),"each lesson has at least four short sections");
ok(lessons.every(x=>x.objectives.length >= 3),"each lesson declares at least three outcomes");
ok(lessons.every(x=>x.sections.every(s=>Array.isArray(s.body)&&s.body.length>=2&&s.body.join(" ").length>=250)),"every section has substantive core reading");
ok(lessons.every(x=>x.sections.every(s=>Array.isArray(s.definitions)&&s.definitions.length>=1)),"every section visibly supplies key words");
ok(lessons.every(x=>x.sections.every(s=>s.outcome&&s.keyIdea&&s.workedExample?.body&&s.summary)),"every section has outcome, key idea, example, and summary");
ok(lessons.every(x=>x.quiz.length>=5),"every lesson ends with a readable assessment of at least five questions");
ok(lessons.every(x=>x.quiz.every(q=>q.options.length===3&&q.options.filter(o=>o.correct).length===1&&q.options.every(o=>o.feedback))),"every assessment question has one correct answer and feedback for all choices");
ok(new Set(lessons.flatMap(x=>x.quiz.map(q=>q.options.findIndex(o=>o.correct)))).size===3,"correct answers use all three positions");
ok(index.includes("content/lessons.js?v=21")&&index.includes("assets/js/app.js?v=21"),"release data and app scripts are cache-busted");
ok(!index.includes("#access")&&!app.includes("renderAccess"),"phone installation instructions are not inside the learning app");
ok(app.includes("SpeechSynthesisUtterance")&&app.includes("Listen to this section")&&app.includes("voice-select")&&app.includes("voice-rate"),"every section supports selectable free built-in narration");
ok(index.includes("shares-intro.wav")===false&&fs.existsSync(path.join(root,"audio/shares-intro.wav")),"polished narration is a static local asset");
ok(sw.includes("investing-foundations-v21")&&sw.includes("content/lessons.js?v=21"),"offline cache includes the complete release");
ok(fs.existsSync(path.join(root,"FAMILY_TEXT_MESSAGE.md"))&&fs.existsSync(path.join(root,"GITHUB_PAGES_RELEASE.md")),"family handoff and GitHub Pages instructions are separate from the app");
process.exitCode = failures ? 1 : 0;
