const fs = require("fs");
const path = require("path");
const vm = require("vm");
const root = path.resolve(__dirname, "..");
let failures = 0;
const ok = (condition, message) => { console.log(`${condition ? "PASS" : "FAIL"} ${message}`); if (!condition) failures++; };
const context = {window:{}}; vm.createContext(context);
for (const file of ["content/course.js","content/lesson-day-2.js","content/quiz-day-2.js","content/glossary.js","content/lessons.js","content/reading-room.js","content/reading-room-expanded.js"]) vm.runInContext(fs.readFileSync(path.join(root,file),"utf8"),context,{filename:file});
const lessons = context.window.IF_LESSONS;
const reading = context.window.IF_READING_ROOM;
const glossary = context.window.IF_GLOSSARY;
const simpleGlossary = context.window.IF_GLOSSARY_SIMPLE;
const index = fs.readFileSync(path.join(root,"index.html"),"utf8");
const app = fs.readFileSync(path.join(root,"assets/js/app.js"),"utf8");
const sw = fs.readFileSync(path.join(root,"service-worker.js"),"utf8");
ok(Array.isArray(lessons) && lessons.length === 14,"exactly 14 complete lessons load");
ok(lessons.map(x=>x.day).join(",") === "1,2,3,4,5,6,7,8,9,10,11,12,13,14","lesson days are ordered 1 through 14");
ok(lessons.every(x=>x.totalMinutes >= 20 && x.totalMinutes <= 30),"each lesson is a 20-30 minute introductory unit");
ok(lessons.every(x=>x.sections.length >= 4),"each lesson has at least four short sections");
ok(lessons.every(x=>x.objectives.length >= 3),"each lesson declares at least three outcomes");
ok(lessons.every(x=>x.sections.every(s=>Array.isArray(s.body)&&s.body.length>=2&&s.body.join(" ").length>=250)),"every section has substantive core reading");
ok(lessons.every(x=>x.sections.every(s=>Array.isArray(s.definitions)&&s.definitions.length>=1)),"every section visibly supplies key words");
ok(lessons.every(x=>x.sections.every(s=>s.outcome&&s.keyIdea&&s.workedExample?.body&&s.summary)),"every section has outcome, key idea, example, and summary");
ok(lessons.every(x=>x.quiz.length>=5),"every lesson ends with a readable assessment of at least five questions");
ok(lessons.every(x=>x.quiz.every(q=>q.options.length===3&&q.options.filter(o=>o.correct).length===1&&q.options.every(o=>o.feedback))),"every assessment question has one correct answer and feedback for all choices");
ok(new Set(lessons.flatMap(x=>x.quiz.map(q=>q.options.findIndex(o=>o.correct)))).size===3,"correct answers use all three positions");
ok(index.includes("content/lessons.js?v=29")&&index.includes("content/reading-room-expanded.js?v=29")&&index.includes("assets/js/app.js?v=29"),"release data, expanded reading room, and app scripts are cache-busted");
ok(!index.includes("#access")&&!app.includes("renderAccess"),"phone installation instructions are not inside the learning app");
ok(app.includes("SpeechSynthesisUtterance")&&app.includes("Listen to this section")&&app.includes("voice-select")&&app.includes("voice-rate"),"every section supports selectable free built-in narration");
ok(index.includes("shares-intro.wav")===false&&fs.existsSync(path.join(root,"audio/shares-intro.wav")),"polished narration is a static local asset");
ok(sw.includes("investing-foundations-v29")&&sw.includes("content/lessons.js?v=29")&&sw.includes("content/reading-room-expanded.js?v=29"),"offline cache includes the complete course and expanded reading room");
ok(fs.existsSync(path.join(root,"FAMILY_TEXT_MESSAGE.md"))&&fs.existsSync(path.join(root,"GITHUB_PAGES_RELEASE.md")),"family handoff and GitHub Pages instructions are separate from the app");
ok(reading.books.length===10,"Reading Room contains exactly ten substantial book guides");
ok(new Set(reading.books.map(book=>book.slug)).size===10,"every reading guide has a unique route");
ok(reading.books.every(book=>book.title&&book.author&&book.year&&book.sourceUrl&&book.bigIdea),"every guide identifies the book and retains source metadata for internal verification");
ok(reading.books.every(book=>book.overview.length>=4&&book.principles.length>=5),"every guide has a sizeable synopsis and at least five principles");
ok(reading.books.every(book=>book.minutes===7&&book.deeperDive?.length>=7&&book.application?.length===3&&book.questions?.length===3),"every book has a complete seven-minute expanded guide structure");
ok(reading.books.every(book=>[...book.overview,...book.principles.map(p=>p.text),book.bigIdea,book.strengths,book.limitations,book.who,book.reflection,...book.deeperDive,...book.application.flatMap(x=>[x.title,x.text]),...book.questions].join(" ").split(/\s+/).length>=1100),"every guide contains at least 1,100 words of original commentary");
ok(Object.keys(reading.interludes).map(Number).sort((a,b)=>a-b).join(",")==="7,9,12,14","four non-book lesson days receive reading labs");
ok(app.includes("#cooldown/")&&app.includes("renderCooldown")&&app.includes("renderReading")&&app.includes("renderBook"),"lessons flow through cooldowns into a permanent library");
ok(!app.includes("training material")&&!app.includes(".pdf"),"the public app does not expose local PDFs or source-folder paths");
const lessonTerms=[...new Set(lessons.flatMap(l=>l.sections.flatMap(s=>(s.definitions||[]).map(item=>(typeof item==="string"?item:item.term).toLowerCase()))))];
ok(glossary.length>=50&&lessonTerms.every(term=>simpleGlossary[term]),"every glossary term has a curated everyday-language explanation");
ok(app.includes("Explain it simply")&&app.includes("<details class=\"glossary-simple\""),"glossary preserves formal definitions and adds accessible expandable explanations");
ok(index.includes("Family v1.3")&&index.includes('name="version" content="1.3"'),"Family Edition v1.3 is visibly and structurally identified");
ok(app.includes("By, ${escapeHTML(book.author)}")&&!app.includes("By ${escapeHTML(book.author)}"),"book credits consistently use title followed by By, author");
ok(app.includes("ORIGINAL CONCEPT MAP")&&app.includes("guide-reading-progress")&&app.includes("guide-roadmap"),"expanded guides include original visuals, progress, and section navigation");
ok(!app.includes("Official publisher information")&&!app.includes("Visit official book page")&&!app.includes("Buy, borrow")&&app.includes("Continue with the copy you already have"),"learner-facing guides contain no book sales or external publisher links");
process.exitCode = failures ? 1 : 0;
